apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pullrequest
spec:
  serviceAccountName: tekton-bot
  pipelineSpec:
    params:
    - name: REPO_URL
      type: string
    - name: PULL_NUMBER
      type: string
    tasks:
    - name: git-clone-test
      params:
      - name: REPO_URL
        value: $(params.REPO_URL)
      - name: PULL_NUMBER
        value: $(params.PULL_NUMBER)
      taskSpec:
        params:
        - name: REPO_URL
          type: string
        - name: PULL_NUMBER
          type: string
        steps:
        - name: git-clone
          image: alpine/git:v2.34.2
          command:
          - /bin/sh
          args:
          - -ce
          - |
            git clone $(inputs.params.REPO_URL) .
            git config --unset-all remote.origin.fetch
            # https://gist.github.com/piscisaureus/3342247
            git config --add remote.origin.fetch '+refs/pull/*/head:refs/remotes/origin/pr/*'
            git fetch origin
            git merge origin/pr/$(inputs.params.PULL_NUMBER)
          workingDir: /workspace
        - name: test
          image: golang:1.18-alpine
          command:
          - /bin/sh
          args:
          - -ce
          - |
            apk add --update make
            make test
          workingDir: /workspace
          volumeMounts:
          - name: go-pkg-mod
            mountPath: /go/pkg/mod
        volumes:
        - name: workspace
          emptyDir: {}
        - name: go-pkg-mod
          hostPath:
            path: /mnt/ssd/data/go/pkg/mod
