apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    always_run: true
    trigger: /test
    rerun_command: /retest
    source: pullrequest.yaml
  postsubmits:
  - name: release
    source: release.yaml
    branches:
    - master
    - ^v\d+\.\d+\.\d+$
