FROM golang:1.15-alpine

RUN apk add --update make curl git bash

RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash && \
  mv kustomize /usr/local/bin/kustomize
