apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: release
spec:
  serviceAccountName: tekton-bot
  pipelineSpec:
    params:
    - description: git url to clone
      name: REPO_URL
      type: string
    - default: master
      description: the base git reference of the pull request
      # TODO: work out why this is set to the tag value
      name: PULL_BASE_REF
      type: string
    tasks:
    - name: build
      params:
      - name: REPO_URL
        value: $(params.REPO_URL)
      - name: PULL_BASE_REF
        value: $(params.PULL_BASE_REF)
      taskSpec:
        params:
        - description: git url to clone
          name: REPO_URL
          type: string
        - default: master
          description: the base git reference of the pull request
          name: PULL_BASE_REF
          type: string
        stepTemplate:
          name: ""
          volumeMounts:
          - name: workspace
            mountPath: /workspace
        steps:
        - name: git-clone
          image: alpine/git:v2.30.0
          command:
          - /bin/sh
          args:
          - -ce
          - |
            mkdir -p $HOME;
            git config --global --add user.name dippynark-bot;
            git config --global --add user.email lukeaddison785@gmail.com;
            git config --global credential.helper store;
            git clone $(inputs.params.REPO_URL) .;
            echo cloned url: $(inputs.params.REPO_URL) to dir: `pwd`;
            git checkout $(inputs.params.PULL_BASE_REF);
            echo checked out PULL_BASE_REF: $(inputs.params.PULL_BASE_REF) to dir: `pwd`
          workingDir: /workspace
        - name: build
          image: dippynark/kfmt-build:v1.0.0
          command:
          - make
          - build
          - test
          workingDir: /workspace
          volumeMounts:
          - name: go-pkg-mod
            mountPath: /go/pkg/mod
        - name: kaniko
          image: gcr.io/kaniko-project/executor:v1.3.0
          args:
          - --dockerfile=Dockerfile
          - --context=dir:///workspace
          - --destination=dippynark/kfmt:$(inputs.params.PULL_BASE_REF)
          - --cache
          - --cache-repo=dippynark/kfmt-cache
          volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
        volumes:
        - name: workspace
          emptyDir: {}
        - name: go-pkg-mod
          hostPath:
            path: /mnt/ssd/data/go/pkg/mod
        - name: kaniko-secret
          secret:
            secretName: tekton-container-registry-auth
            items:
            - key: .dockerconfigjson
              path: config.json
