apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: release
spec:
  serviceAccountName: tekton-bot
  pipelineSpec:
    params:
    - description: git url to clone
      name: REPO_URL
      type: string
    - default: master
      description: git revision to checkout (branch, tag, sha, ref…)
      name: revision
      type: string
    tasks:
    - name: build
      params:
      - name: REPO_URL
        value: $(params.REPO_URL)
      - name: revision
        value: $(params.revision)
      taskSpec:
        params:
        - description: git url to clone
          name: REPO_URL
          type: string
        - default: master
          description: git revision to checkout (branch, tag, sha, ref…)
          name: revision
          type: string
        stepTemplate:
          name: ""
          volumeMounts:
          - name: workspace
            mountPath: /workspace
        steps:
        - name: git-clone
          image: alpine/git:v2.30.0
          command:
          - /bin/sh
          args:
          - -ce
          - |
            mkdir -p $HOME;
            git config --global --add user.name dippynark-bot;
            git config --global --add user.email lukeaddison785@gmail.com;
            git config --global credential.helper store;
            git clone $(inputs.params.REPO_URL) .;
            echo cloned url: $(inputs.params.REPO_URL) to dir: `pwd`;
            git checkout $(inputs.params.revision);
            echo checked out revision: $(inputs.params.revision) to dir: `pwd`
          workingDir: /workspace
        - name: build
          image: dippynark/kfmt-build:v1.0.0
          command:
          - make
          - build
          - test
          workingDir: /workspace
          volumeMounts:
          - name: go-pkg-mod
            mountPath: /go/pkg/mod
        volumes:
        - name: workspace
          emptyDir: {}
        - name: go-pkg-mod
          hostPath:
            path: /mnt/ssd/data/go/pkg/mod


        # stepTemplate:
        #   name: ""
        #   volumeMounts:
        #   # Mount cannot intersect with WORKDIR of Dockerfile
        #   # https://github.com/GoogleContainerTools/kaniko/issues/946
        #   - mountPath: /workspace
        #     name: workspace
        #
        # - name: kaniko
        #   image: gcr.io/kaniko-project/executor:v1.3.0
        #   args:
        #   - --dockerfile=Dockerfile
        #   - --context=dir:///workspace/source
        #   - --destination=dippynark/kfmt-build:$(inputs.params.revision)
        #   - --cache
        #   - --cache-repo=dippynark/kfmt-build-cache
        #   volumeMounts:
        #   - name: kaniko-secret
        #     mountPath: /kaniko/.docker
        # volumes:
        # - name: workspace
        #   emptyDir: {}
        # - name: kaniko-secret
        #   secret:
        #     secretName: tekton-container-registry-auth
        #     items:
        #     - key: .dockerconfigjson
        #       path: config.json